### Disclaimer:
**This project uses the Boston Housing dataset for educational purposes only. 
The dataset has known ethical concerns and has been deprecated in scikit-learn.**

### Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [18]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

X,y = load_iris(return_X_y=True)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=45)

classifier = KNeighborsClassifier()
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

Accuracy: 0.9473684210526315


### Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

In [19]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

boston = load_boston()
X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.3, random_state=42)

knn_reg = KNeighborsRegressor(n_neighbors=5)
knn_reg.fit(X_train, y_train)
y_pred = knn_reg.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))


MSE: 30.94554736842105


### Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [20]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

#load the iris dataset
X,y = load_iris(return_X_y=True)

#train test split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=45)

# Create a list of K values to try
k_values = list(range(1, 25))

# Create an empty list to store cross-validation scores
cv_scores = []

# Iterate over each K value and perform cross-validation
for k in k_values:
    knn_classifier = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn_classifier, X_train, y_train, cv=5, scoring='accuracy')
    cv_scores.append(scores.mean())

# Find the optimal K value with the highest cross-validation score
optimal_k = k_values[cv_scores.index(max(cv_scores))]

print(f"The optimal K value is {optimal_k} with a cross-validation accuracy of {max(cv_scores)}")

# Finally, you can train the KNN classifier with the optimal K on the full training set and evaluate it on the test set.
optimal_knn_classifier = KNeighborsClassifier(n_neighbors=optimal_k)
optimal_knn_classifier.fit(X_train, y_train)
y_pred = optimal_knn_classifier.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

The optimal K value is 5 with a cross-validation accuracy of 0.9640316205533598
Accuracy: 0.9473684210526315


#### Observation: 
With the optimal Value of k the accuracy of the model is increased from 94.73 to 96.40

### Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

In [21]:
from sklearn.neighbors import KNeighborsRegressor
# from sklearn.datasets import load_boston
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler

#Since the load boston dataset is removed from sklearn we are using dataset url
import pandas as pd
import numpy as np
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

#train test split
X_train,X_test,y_train,y_test = train_test_split(data,target,test_size=0.25,random_state=45)

#Standardization of numerical columns by using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Applying KNN regresssor
regressor = KNeighborsRegressor()
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)

#Checking the prediction r2 score of the model
print(f"R2 Score: {r2_score(y_test, y_pred)}")

R2 Score: 0.758193487336346


**Observation : After Scaling the R2 increased from 45.99 to 75.81**

### Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [22]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

X,y = load_iris(return_X_y=True)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=45)

# Create a KNN classifier with weighted voting
classifierr = KNeighborsClassifier(weights='distance')

# Fit the classifier on the training data
classifierr.fit(X_train, y_train)

# Make predictions on the test data
y_pred = classifierr.predict(X_test)

# Evaluate the accuracy of the model
accuracy = classifierr.score(X_test, y_test)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.95


### Q6. Implement a function to standardise the features before applying KNN classifier.

In [23]:
from sklearn.preprocessing import StandardScaler

def standardize_features(X_train, X_test):
    scaler = StandardScaler()
    X_train_std = scaler.fit_transform(X_train)
    X_test_std = scaler.transform(X_test)
    return X_train_std, X_test_std

In [24]:
X_train_std, X_test_std = standardize_features(X_train, X_test)
print("Standardized Training Data:")
print(X_train_std)
print("Standardized Testing Data:")
print(X_test_std)

Standardized Training Data:
[[ 0.65250979 -0.34643465  0.29999603  0.12464034]
 [-1.2770241   0.08952806 -1.24810637 -1.3240097 ]
 [-0.43285303  2.48732297 -1.36278062 -1.3240097 ]
 [-0.07106542 -0.78239737  0.07064753 -0.00705511]
 [-1.15642824 -0.1284533  -1.36278062 -1.3240097 ]
 [ 1.25548913  0.08952806  0.64401879  0.38803126]
 [-1.03583237 -1.65432279 -0.27337523 -0.27044603]
 [-0.9152365   1.39741619 -1.30544349 -1.06061878]
 [ 0.65250979 -0.78239737  0.87336729  0.9148131 ]
 [ 0.17012631 -1.87230414  0.12798466 -0.27044603]
 [ 2.22025607  1.61539755  1.67608706  1.30989947]
 [-1.15642824  1.17943484 -1.36278062 -1.45570516]
 [-1.2770241  -0.1284533  -1.36278062 -1.19231424]
 [-0.31225716 -0.1284533   0.41467029  0.38803126]
 [ 0.65250979 -0.56441601  1.04537867  1.17820401]
 [-0.67404476  1.39741619 -1.30544349 -1.3240097 ]
 [ 1.01429739  0.52549077  1.1027158   1.70498585]
 [-0.9152365   1.61539755 -1.30544349 -1.19231424]
 [-1.39761997  0.30750941 -1.24810637 -1.3240097 ]
 [-

### Q7. Write a Python function to calculate the euclidean distance between two points.

In [25]:
def euclidean_distance(x,y):
    x1,x2=x
    y1,y2=y
    dist = np.sqrt((x2-x1)**2 +(y2-y1)**2)
    return dist

point1 = (1, 2)
point2 = (4, 6)
distance = euclidean_distance(point1, point2)
print(f"Euclidean Distance: {distance:.2f}")

Euclidean Distance: 2.24


### Q8. Write a Python function to calculate the manhattan distance between two points.

In [26]:
def manhattan_distance(x,y):
    x1,x2=x
    y1,y2=y
    dist = np.abs(x2-x1) + np.abs(y2-y1)
    return dist

point1 = (1, 2)
point2 = (4, 6)
distance = manhattan_distance(point1, point2)
print(f"Manhattan Distance: {distance:.2f}")

Manhattan Distance: 3.00


### Explanation of .2f:
This is part of Python’s f-string formatting.  

**.2f means:**
* Format the floating-point number (distance)
* Show 2 digits after the decimal point

##### Example:

* If distance = 7.12345, it will print: "Manhattan Distance: 7.12"

* If distance = 7.0, it will print: "Manhattan Distance: 7.00"