Consider the below code to answer further questions:  
import numpy as np  
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]  
array_list = np.array(object = list_)  

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [17]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [18]:
print("Type of list_ Variable : ",type(list_))
print("Type of array_list Variable : ",type(array_list))
print("Data Type of elements in array_list Variable : ",array_list.dtype)

Type of list_ Variable :  <class 'list'>
Type of array_list Variable :  <class 'numpy.ndarray'>
Data Type of elements in array_list Variable :  <U1


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [19]:
for i in list_:
    print(f"Type of list_ {i} Variable : {type(i)}")
    
for j in array_list:
    print(f"Type of array_list {j} Variable : {type(j)}")

Type of list_ 1 Variable : <class 'str'>
Type of list_ 2 Variable : <class 'str'>
Type of list_ 3 Variable : <class 'str'>
Type of list_ 4 Variable : <class 'str'>
Type of list_ 5 Variable : <class 'str'>
Type of array_list 1 Variable : <class 'numpy.str_'>
Type of array_list 2 Variable : <class 'numpy.str_'>
Type of array_list 3 Variable : <class 'numpy.str_'>
Type of array_list 4 Variable : <class 'numpy.str_'>
Type of array_list 5 Variable : <class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

Ans) list_ contains strings like '1', '2' → so its elements are of type str.  

After converting array_list using dtype=int, each element becomes an integer, stored as a NumPy integer type (e.g., numpy.int64).

In [20]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for item in list_:
    print(f"{item}: {type(item)}")

print("\nData types of elements in array_list:")
for item in array_list:
    print(f"{item}: {type(item)}")


Data types of elements in list_:
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>

Data types of elements in array_list:
1: <class 'numpy.int32'>
2: <class 'numpy.int32'>
3: <class 'numpy.int32'>
4: <class 'numpy.int32'>
5: <class 'numpy.int32'>


In [21]:
import numpy as np  
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]  
num_array = np.array(object = num_list)  

### Q4. Write a code to find the following characteristics of variable, num_array:   
(i) shape  
(ii) size

Ans)**shape attribute:**  
The shape attribute of a NumPy array returns a tuple representing the dimensions of the array.   
It provides the number of elements along each axis (dimension) of the array.  
The length of the shape tuple corresponds to the number of dimensions (axes) of the array.  
The shape attribute is helpful in understanding the structure and dimensions of multi-dimensional arrays.  
The shape attribute can be accessed using the .shape notation.  

**size attribute:**  
The size attribute of a NumPy array returns the total number of elements present in the array.  
It represents the total size or length of the array when considering all its dimensions.  
The size attribute is similar to the len() function used for Python lists, but it works on multi-dimensional arrays as well.  
It is a scalar value (integer) representing the total count of elements in the array.  
The size attribute can be accessed using the .size notation.   

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
num_array.shape

(2, 3)

In [24]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


**np.zeros()**  is a function used to create an array filled with zeros.
The function allows you to specify the shape and data type of the array you want to create.
It is particularly useful when you want to initialize an array with all elements set to zero.

In [25]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr.size
arr.shape

(3, 3)

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

**np.eye()** is a function used to create an identity matrix, which is a square matrix with ones on the main diagonal (from the top-left to the bottom-right) and zeros elsewhere.
The identity matrix is denoted by "I" or "𝐈" and has a unique property that when multiplied with any other matrix, it leaves the other matrix unchanged

In [27]:
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr1.shape

(5, 5)

In [29]:
arr1.size

25